import { Inter } from "next/font/google";
import Head from "next/head";
import { FooterLinks } from "../components/Footer";
import { AuthenticationForm } from "../components/logincomp";
import { HeaderMegaMenu } from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const links = [
  {
    title: "abcd",
    links: [
      {
        label: "abcd",
        link: "asjd",
      },
    ],
  },
  {
    title: "abcd",
    links: [
      {
        label: "abcd",
        link: "asjd",
      },
    ],
  },
  {
    title: "abcd",
    links: [
      {
        label: "abcd",
        link: "asjd",
      },
    ],
  },
];

export default function SignIn() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <NavbarSimple /> */}
      <HeaderMegaMenu />
      <AuthenticationForm />
      <FooterLinks data={links} />
    </>
  );
}
